language: java
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "ispw-becrafter"
    token:
      secure: "a60b7c72cdd1cfda416d9572c777add7db228d59"
script: 
  - ant build
  - sonar-scanner